<template>
  <div class="setting-panel-gui">
    <g-field-collapse
      label="图形"
    >
      <g-field
        :level="2"
        label="刻度最小值"
      >
        <g-input-number
          v-model="config.graphical.min"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label="刻度最大值"
      >
        <g-input-number
          v-model="config.graphical.max"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label="开始角度"
      >
        <g-input-number
          v-model="config.graphical.startAngle"
          :step="1"
          suffix="度"
        />
      </g-field>
      <g-field
        :level="2"
        label="结束角度"
      >
        <g-input-number
          v-model="config.graphical.endAngle"
          :step="1"
          suffix="度"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.pointer.show"
      :toggle="true"
      label="指针"
    >
      <g-field
        :level="2"
        label="长度"
      >
        <g-input-number
          v-model="config.pointer.length"
          :min="0"
          :max="100"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="宽度"
      >
        <g-input-number
          v-model="config.pointer.width"
          :min="0"
          :max="100"
          :step="1"
          suffix="px"
        />
      </g-field>
      <g-field
        :level="2"
        label="水平偏移量"
      >
        <g-input-number
          v-model="config.pointer.horizontal"
          :min="-1000"
          :max="100"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="垂直偏移量"
      >
        <g-input-number
          v-model="config.pointer.vertical"
          :min="-1000"
          :max="100"
          :step="1"
          suffix="%"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.progress.show"
      :toggle="true"
      label="进度条"
    >
      <g-field
        :level="2"
        label="两端显示成圆形"
      >
        <n-switch
          v-model:value="config.progress.roundCap"
        />
      </g-field>
      <g-field
        :level="2"
        label="进度条颜色"
      >
        <g-color-picker
          v-model="config.progress.color"
        />
      </g-field>
      <g-field-collapse
        label="边框样式"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.progress.border.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="宽度"
        >
          <g-input-number
            v-model="config.progress.border.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.progress.border.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      label="轴线"
    >
      <g-field
        :level="2"
        label="宽度"
      >
        <g-input-number
          v-model="config.axisLine.width"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label="颜色"
      >
        <g-color-picker
          v-model="config.axisLine.color"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      label="分割线"
    >
      <g-field
        :level="2"
        label="长度"
      >
        <g-input-number
          v-model="config.splitLine.length"
          :step="1"
        />
      </g-field>
      <g-field-collapse
        label="线型"
      >
        <g-field
          :level="2"
          label="宽度"
        >
          <g-input-number
            v-model="config.splitLine.lineStyle.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.splitLine.lineStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.axisTick.show"
      :toggle="true"
      label="轴刻度"
    >
      <g-field
        :level="2"
        label="间隔数"
      >
        <g-input-number
          v-model="config.axisTick.splitNumber"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field-collapse
        label="线型"
      >
        <g-field
          :level="2"
          label="宽度"
        >
          <g-input-number
            v-model="config.axisTick.lineStyle.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.axisTick.lineStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.axisLabel.show"
      :toggle="true"
      label="轴标签"
    >
      <g-field
        :level="2"
        label="距离"
      >
        <g-input-number
          v-model="config.axisLabel.distance"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label="颜色"
      >
        <g-color-picker
          v-model="config.axisLabel.color"
        />
      </g-field>
      <g-field
        :level="2"
        label="字体"
      >
        <g-select
          v-model="config.axisLabel.fontFamily"
          :data="fontFamilys"
        />
      </g-field>
      <g-field
        :level="2"
        label="粗细"
      >
        <g-select
          v-model="config.axisLabel.fontWeight"
          :data="fontWeights"
        />
      </g-field>
      <g-field
        :level="2"
        label="大小"
      >
        <g-input-number
          v-model="config.axisLabel.fontSize"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.title.show"
      :toggle="true"
      label="标题"
    >
      <g-field
        :level="2"
        label="水平偏移量"
      >
        <g-input-number
          v-model="config.title.horizontal"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="垂直偏移量"
      >
        <g-input-number
          v-model="config.title.vertical"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="文本内容"
      >
        <g-input
          v-model="config.title.text"
        />
      </g-field>
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.title.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-select
            v-model="config.title.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
        <g-field
          :level="2"
          label="大小"
        >
          <g-input-number
            v-model="config.title.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.title.textStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.content.show"
      :toggle="true"
      label="内容"
    >
      <g-field
        :level="2"
        label="水平偏移量"
      >
        <g-input-number
          v-model="config.content.horizontal"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="垂直偏移量"
      >
        <g-input-number
          v-model="config.content.vertical"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.content.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-select
            v-model="config.content.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
        <g-field
          :level="2"
          label="大小"
        >
          <g-input-number
            v-model="config.content.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.content.textStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
  lineStyles,
  fontFamilys,
  fontWeights,
} from '@/data/select-options'
import { DashboardPie } from './dashboard-pie'

export default defineComponent({
  name: 'VDashboardPieProp',
  props: {
    com: {
      type: Object as PropType<DashboardPie>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    return {
      config,

      lineStyles,
      fontFamilys,
      fontWeights,
    }
  },
})
</script>
