<template>
  <div class="setting-panel-gui">
    <g-field-collapse
      tooltip="请选择您系统有的字体，如果您系统无此字体，标题将会显示默认字体"
      label="全局"
    >
      <g-field
        :level="2"
        label="字体"
      >
        <g-select
          v-model="config.global.fontFamily"
          :data="fontFamilys"
        />
      </g-field>
      <g-field
        :level="2"
        label="内半径"
      >
        <g-input-number
          v-model="config.global.polarInsideRadius"
          :min="0"
          :step="1"
          suffix="px"
        />
      </g-field>
      <g-field
        :level="2"
        label="外半径"
      >
        <g-input-number
          v-model="config.global.polarOutsideRadius"
          :min="0"
          :max="100"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field-collapse
        v-model="config.global.background.show"
        :toggle="true"
        label="背景色"
      >
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.global.background.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.global.diffrentColor"
        label="彩色饼图"
        mode="layout"
        default-layout="horizontal"
        :features="['vertical','horizontal','copy','add','remove']"
        :list="config.global.colorList"
        :min="1"
        :max="8"
        tab="颜色"
        :add-item="handleAddColor"
        :toggle="true"
      >
        <template #default="slotProps">
          <g-field
            :level="2"
            label="颜色"
          >
            <!-- {{ slotProps.item }} -->
            <g-color-picker
              v-model="slotProps.item.value"
            />
          </g-field>
        </template>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.label.show"
      :toggle="true"
      label="柱子标注"
    >
      <g-field
        :level="2"
        label="位置"
      >
        <g-select
          v-model="config.label.position"
          :data="echartsLablePositions"
        />
      </g-field>
      <g-field
        :level="2"
        label="文本样式"
        :is-flat="true"
      >
        <g-input-number
          v-model="config.label.textStyle.fontSize"
          :min="12"
          :max="100"
          :step="1"
          suffix="px"
          inline="inline"
          label="字号"
        />
        <g-color-picker
          v-model="config.label.textStyle.color"
          inline="inline"
          label="颜色"
        />
        <g-select
          v-model="config.label.textStyle.fontWeight"
          :data="fontWeights"
          inline="inline"
          label="字体粗细"
        />
      </g-field>
      <g-field
        :level="2"
        label="水平偏移"
      >
        <g-slider
          v-model="config.label.offsetX"
          :min="-1000"
          :max="1000"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label="垂直偏移"
      >
        <g-slider
          v-model="config.label.offsetY"
          :min="-1000"
          :max="1000"
          :step="1"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.radiusAxis.show"
      :toggle="true"
      label="径向轴"
    >
      <g-field
        :level="2"
        label="类型"
      >
        <n-radio-group
          v-model:value="config.radiusAxis.type"
          size="small"
        >
          <n-radio-button
            v-for="em in radiusAxisTypes"
            :key="em.id"
            :value="em.id"
          >
            {{ em.value }}
          </n-radio-button>
        </n-radio-group>
      </g-field>
      <g-field-collapse
        v-model="config.radiusAxis.title.show"
        :toggle="true"
        label="轴标题"
      >
        <g-field
          :level="2"
          label="标题显示"
        >
          <g-input
            v-model="config.radiusAxis.title.name"
          />
        </g-field>
        <g-field
          :level="2"
          label="位置"
        >
          <g-select
            v-model="config.radiusAxis.title.location"
            :data="titleLocations"
          />
        </g-field>
        <g-field
          :level="2"
          label="展示方式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.radiusAxis.title.display.rotate"
            :min="0"
            :max="360"
            :step="1"
            suffix="度"
            inline="inline"
            label="旋转"
          />
          <g-input-number
            v-model="config.radiusAxis.title.display.offset"
            :min="-1000"
            :max="1000"
            :step="1"
            suffix="px"
            inline="inline"
            label="偏移"
          />
        </g-field>
        <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.radiusAxis.title.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="字号"
          />
          <g-color-picker
            v-model="config.radiusAxis.title.textStyle.color"
            inline="inline"
            label="颜色"
          />
          <g-select
            v-model="config.radiusAxis.title.textStyle.fontWeight"
            :data="fontWeights"
            inline="inline"
            label="字体粗细"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.radiusAxis.axisLine.show"
        :toggle="true"
        label="轴线"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.radiusAxis.axisLine.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.radiusAxis.axisLine.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.radiusAxis.axisLine.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.radiusAxis.axisTick.show"
        :toggle="true"
        label="轴刻度"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.radiusAxis.axisTick.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.radiusAxis.axisTick.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.radiusAxis.axisTick.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.radiusAxis.axisLabel.show"
        :toggle="true"
        label="轴标签"
      >
        <g-field
          v-if="config.radiusAxis.type === 'time'"
          :level="2"
          tooltip="时间请参照 YYYY/MM/DD HH:mm:ss"
          label="显示格式"
        >
          <g-select
            v-model="config.radiusAxis.axisLabel.timeFormat"
            :data="timeFormats"
          />
        </g-field>
        <g-field
          :level="2"
          label="两端留白"
        >
          <n-switch
            v-model:value="config.radiusAxis.axisLabel.boundaryGap"
          />
        </g-field>
        <g-field
          :level="2"
          tooltip="默认会采用标签不重叠的策略间隔显示标签，可以设置成 0 强制显示所有标签。"
          label="间隔"
        >
          <g-select-suggest
            v-model="config.radiusAxis.axisLabel.interval"
            :data="selectSuggests"
            :filters="['auto','0','1','2']"
          />
        </g-field>
        <g-field
          :level="2"
          label="展示方式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.radiusAxis.axisLabel.display.rotate"
            :min="0"
            :max="100"
            :step="1"
            suffix="度"
            inline="inline"
            label="旋转"
          />
          <g-input-number
            v-model="config.radiusAxis.axisLabel.display.margin"
            :min="-1000"
            :max="1000"
            :step="1"
            suffix="px"
            inline="inline"
            label="偏移"
          />
        </g-field>
        <g-field
          :level="2"
          label="对齐方式"
        >
          <g-select
            v-model="config.radiusAxis.axisLabel.align"
            :data="hAligns"
          />
        </g-field>
        <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.radiusAxis.axisLabel.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="字号"
          />
          <g-color-picker
            v-model="config.radiusAxis.axisLabel.textStyle.color"
            inline="inline"
            label="颜色"
          />
          <g-select
            v-model="config.radiusAxis.axisLabel.textStyle.fontWeight"
            :data="fontWeights"
            inline="inline"
            label="字体粗细"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.radiusAxis.grid.show"
        :toggle="true"
        label="网格线"
      >
        <g-field
          :level="2"
          label="线型样式"
          :is-flat="true"
        >
          <g-select
            v-model="config.radiusAxis.grid.line.type"
            :data="lineStyles"
            inline="inline"
            label="类型"
          />
          <g-input-number
            v-model="config.radiusAxis.grid.line.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="粗细"
          />
          <g-color-picker
            v-model="config.radiusAxis.grid.line.color"
            inline="inline-single"
            label="颜色"
          />
          <g-input-number
            v-if="config.radiusAxis.grid.line.type === 'dashed'"
            v-model="config.radiusAxis.grid.line.dashedLength"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="长度"
          />
          <g-input-number
            v-if="config.radiusAxis.grid.line.type === 'dashed'"
            v-model="config.radiusAxis.grid.line.dashedSpace"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="间距"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.angleAxis.show"
      :toggle="true"
      label="角轴"
    >
      <g-field
        :level="2"
        label="显示范围"
        :is-flat="true"
      >
        <g-select-suggest
          v-model="config.angleAxis.extent.min"
          :data="selectSuggests"
          :filters="['auto','dataMin']"
          inline="inline"
          label="最小值"
        />
        <g-select-suggest
          v-model="config.angleAxis.extent.max"
          :data="selectSuggests"
          :filters="['auto','dataMax']"
          inline="inline"
          label="最大值"
        />
      </g-field>
      <g-field
        :level="2"
        tooltip="这是个预估值，实际显示会做调整，可以设置成 0 强制显示所有标签。"
        label="标签数量"
      >
        <g-input-number
          v-model="config.angleAxis.splitNumber"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label="起始角度"
      >
        <g-input-number
          v-model="config.angleAxis.startAngle"
          :min="0"
          :max="360"
          :step="1"
          suffix="度"
        />
      </g-field>
      <g-field
        :level="2"
        label="顺时针显示"
      >
        <n-switch
          v-model:value="config.angleAxis.clockwise"
        />
      </g-field>
      <g-field-collapse
        v-model="config.angleAxis.axisLine.show"
        :toggle="true"
        label="轴线"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.angleAxis.axisLine.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.angleAxis.axisLine.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.angleAxis.axisLine.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.angleAxis.axisTick.show"
        :toggle="true"
        label="轴刻度"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.angleAxis.axisTick.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.angleAxis.axisTick.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.angleAxis.axisTick.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.angleAxis.axisLabel.show"
        :toggle="true"
        label="轴标签"
      >
        <g-field
          :level="2"
          tooltip="整数参照 d, 浮点参照 .1f"
          label="显示格式"
        >
          <g-select
            v-model="config.angleAxis.axisLabel.valueFormat"
            :data="valueFormats"
          />
        </g-field>
        <g-field
          :level="2"
          label="两端间距"
        >
          <g-input-number
            v-model="config.angleAxis.axisLabel.boundaryGap"
            :min="0"
            :max="100"
            :step="1"
            suffix="%"
          />
        </g-field>
        <g-field
          :level="2"
          label="展示方式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.angleAxis.axisLabel.display.rotate"
            :min="0"
            :max="360"
            :step="1"
            suffix="度"
            inline="inline"
            label="旋转"
          />
          <g-input-number
            v-model="config.angleAxis.axisLabel.display.margin"
            :min="-1000"
            :max="1000"
            :step="1"
            suffix="px"
            inline="inline"
            label="偏移"
          />
        </g-field>
        <g-field
          :level="2"
          label="对齐方式"
        >
          <g-select
            v-model="config.angleAxis.axisLabel.align"
            :data="hAligns"
          />
        </g-field>
        <g-field
          :level="2"
          label="文本样式"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.angleAxis.axisLabel.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="字号"
          />
          <g-color-picker
            v-model="config.angleAxis.axisLabel.textStyle.color"
            inline="inline"
            label="颜色"
          />
          <g-select
            v-model="config.angleAxis.axisLabel.textStyle.fontWeight"
            :data="fontWeights"
            inline="inline"
            label="字体粗细"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.angleAxis.grid.show"
        :toggle="true"
        label="网格线"
      >
        <g-field
          :level="2"
          label="线型样式"
          :is-flat="true"
        >
          <g-select
            v-model="config.angleAxis.grid.line.type"
            :data="lineStyles"
            inline="inline"
            label="类型"
          />
          <g-input-number
            v-model="config.angleAxis.grid.line.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="粗细"
          />
          <g-color-picker
            v-model="config.angleAxis.grid.line.color"
            inline="inline-single"
            label="颜色"
          />
          <g-input-number
            v-if="config.angleAxis.grid.line.type === 'dashed'"
            v-model="config.angleAxis.grid.line.dashedLength"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="长度"
          />
          <g-input-number
            v-if="config.angleAxis.grid.line.type === 'dashed'"
            v-model="config.angleAxis.grid.line.dashedSpace"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="间距"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.tooltip.show"
      :toggle="true"
      label="提示框"
    >
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字号"
        >
          <g-input-number
            v-model="config.tooltip.textStyle.fontSize"
            :min="12"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.tooltip.textStyle.color"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体粗细"
        >
          <g-select
            v-model="config.tooltip.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        label="弹框背景"
      >
        <g-field
          :level="2"
          label="背景边距"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.tooltip.background.padding.h"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="水平"
          />
          <g-input-number
            v-model="config.tooltip.background.padding.v"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="垂直"
          />
        </g-field>
        <g-field
          :level="2"
          label="背景色"
        >
          <g-color-picker
            v-model="config.tooltip.background.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.tooltip.pointer.show"
        :toggle="true"
        label="轴指示器"
      >
        <g-field
          :level="2"
          label="线型样式"
          :is-flat="true"
        >
          <g-select
            v-model="config.tooltip.pointer.line.type"
            :data="lineStyles"
            inline="inline"
            label="类型"
          />
          <g-input-number
            v-model="config.tooltip.pointer.line.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="粗细"
          />
          <g-color-picker
            v-model="config.tooltip.pointer.line.color"
            inline="inline-single"
            label="颜色"
          />
          <g-input-number
            v-if="config.tooltip.pointer.line.type === 'dashed'"
            v-model="config.tooltip.pointer.line.dashedLength"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="长度"
          />
          <g-input-number
            v-if="config.tooltip.pointer.line.type === 'dashed'"
            v-model="config.tooltip.pointer.line.dashedSpace"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="间距"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.legend.show"
      :toggle="true"
      label="图例"
    >
      <g-field
        :level="2"
        label="位置"
      >
        <g-select
          v-model="config.legend.position"
          :data="legendLocations"
        />
      </g-field>
      <g-field
        :level="2"
        label="布局方式"
      >
        <n-radio-group
          v-model:value="config.legend.orient"
          size="small"
        >
          <n-radio-button
            v-for="em in orients"
            :key="em.id"
            :value="em.id"
          >
            {{ em.value }}
          </n-radio-button>
        </n-radio-group>
      </g-field>
      <g-field
        :level="2"
        label="文本样式"
        :is-flat="true"
      >
        <g-input-number
          v-model="config.legend.textStyle.fontSize"
          :min="0"
          :max="100"
          :step="1"
          suffix="px"
          inline="inline"
          label="字号"
        />
        <g-color-picker
          v-model="config.legend.textStyle.color"
          inline="inline"
          label="颜色"
        />
        <g-select
          v-model="config.legend.textStyle.fontWeight"
          :data="fontWeights"
          inline="inline-single"
          label="字体粗细"
        />
      </g-field>
      <g-field-collapse
        v-model="config.legend.symbol.show"
        :toggle="true"
        label="图例图标"
      >
        <g-field
          :level="2"
          label="图标"
        >
          <g-select-shape
            v-model="config.legend.symbol.icon"
            :shapes="legendIcons"
          />
        </g-field>
        <g-field
          :level="2"
          label="宽度"
        >
          <g-input-number
            v-model="config.legend.symbol.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="高度"
        >
          <g-input-number
            v-model="config.legend.symbol.height"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="间隔"
        >
          <g-input-number
            v-model="config.legend.symbol.gap"
            :min="-1000"
            :max="1000"
            :step="1"
            suffix="px"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        v-model="config.legend.page.enabled"
        :toggle="true"
        label="翻页功能"
      >
        <g-field
          :level="2"
          label="容器尺寸"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.legend.page.size.width"
            :min="0"
            :max="1000"
            :step="1"
            suffix="px"
            inline="inline"
            label="宽度"
          />
          <g-input-number
            v-model="config.legend.page.size.height"
            :min="0"
            :max="1000"
            :step="1"
            suffix="px"
            inline="inline"
            label="高度"
          />
        </g-field>
        <g-field
          :level="2"
          label="翻页按钮"
          :is-flat="true"
        >
          <g-input-number
            v-model="config.legend.page.button.size"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
            inline="inline"
            label="尺寸"
          />
          <g-color-picker
            v-model="config.legend.page.button.color"
            inline="inline"
            label="颜色"
          />
          <g-color-picker
            v-model="config.legend.page.button.inactiveColor"
            inline="inline-single"
            label="禁用颜色"
          />
        </g-field>
        <g-field
          :level="2"
          label="页码颜色"
        >
          <g-color-picker
            v-model="config.legend.page.pageNumColor"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      label="系列"
      mode="layout"
      default-layout="horizontal"
      :features="['vertical','horizontal','copy','add','remove']"
      :list="config.series"
      :min="1"
      :max="5"
      tab="系列"
      :add-item="handleAddSeriesItem"
    >
      <template #default="slotProps">
        <g-field
          :level="2"
          label="系列名称"
        >
          <g-input
            v-model="slotProps.item.name"
          />
        </g-field>
        <g-field-collapse
          label="颜色配置"
        >
          <g-field
            :level="2"
            label="填充类型"
          >
            <n-radio-group
              v-model:value="slotProps.item.color.type"
              size="small"
            >
              <n-radio-button
                v-for="em in fillTypes"
                :key="em.id"
                :value="em.id"
              >
                {{ em.value }}
              </n-radio-button>
            </n-radio-group>
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'solid'"
            :level="2"
            label="颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.value"
            />
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'gradient'"
            :level="2"
            label="开始颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.from"
            />
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'gradient'"
            :level="2"
            label="中间颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.middle"
            />
          </g-field>
          <g-field
            v-if="slotProps.item.color.type === 'gradient'"
            :level="2"
            label="结束颜色"
          >
            <g-color-picker
              v-model="slotProps.item.color.to"
            />
          </g-field>
        </g-field-collapse>
      </template>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.animation.enabled"
      :toggle="true"
      label="动画"
    >
      <g-field
        :level="2"
        label="持续时间"
      >
        <g-input-number
          v-model="config.animation.duration"
          :min="0"
          :step="100"
          suffix="ms"
        />
      </g-field>
      <g-field
        :level="2"
        label="缓动效果"
      >
        <g-select
          v-model="config.animation.easing"
          :data="animationEasings"
        />
      </g-field>
      <g-field
        :level="2"
        label="延迟"
      >
        <g-input-number
          v-model="config.animation.delay"
          :min="0"
          :step="100"
          suffix="ms"
        />
      </g-field>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef, computed } from 'vue'
import {
  fontFamilys,
  selectSuggests,
  echartsLablePositions,
  fontWeights,
  axisTypes,
  titleLocations,
  lineStyles,
  timeFormats,
  hAligns,
  valueFormats,
  legendLocations,
  orients,
  legendIcons,
  fillTypes,
  animationEasings,
} from '@/data/select-options'
import { PolarBar, PolarBarSeries,colorItem } from './polar-bar'

export default defineComponent({
  name: 'VPolarBarProp',
  props: {
    com: {
      type: Object as PropType<PolarBar>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    const radiusAxisTypes = computed(() => {
      return axisTypes.filter(m => m.id !== 'value')
    })

    const handleAddSeriesItem = () => {
      return new PolarBarSeries(`系列${config.value.series.length + 1}`)
    }

    const handleAddColor = () => {
      return new colorItem('#fff')
    }

    return {
      config,
      radiusAxisTypes,
      handleAddSeriesItem,
      handleAddColor,
      fontFamilys,
      selectSuggests,
      echartsLablePositions,
      fontWeights,
      axisTypes,
      titleLocations,
      lineStyles,
      timeFormats,
      hAligns,
      valueFormats,
      legendLocations,
      orients,
      legendIcons,
      fillTypes,
      animationEasings,
    }
  },
})
</script>
