<template>
  <div class="setting-panel-gui">
    <!-- <g-field-collapse
      label="图形"
    >
      <g-field-collapse
        label="图表边距"
      >
        <g-field
          :level="2"
          label="上"
        >
          <g-input-number
            v-model="config.graphical.margin.top"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="下"
        >
          <g-input-number
            v-model="config.graphical.margin.bottom"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="左"
        >
          <g-input-number
            v-model="config.graphical.margin.left"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="右"
        >
          <g-input-number
            v-model="config.graphical.margin.right"
            :step="1"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse> -->
    <g-field-collapse
      label="进度条"
    >
      <g-field
        :level="2"
        label="两端显示成圆形"
      >
        <n-switch
          v-model:value="config.progress.roundCap"
        />
      </g-field>
      <g-field
        :level="2"
        label="进度条宽度"
      >
        <g-input-number
          v-model="config.progress.lineWidth"
          :min="0"
          :max="100"
          :step="1"
        />
      </g-field>
      <g-field
        :level="2"
        label="进度条颜色"
      >
        <g-color-picker
          v-model="config.progress.color"
        />
      </g-field>
      <g-field
        :level="2"
        label="未完成进度颜色"
      >
        <g-color-picker
          v-model="config.progress.incompleteColor"
        />
      </g-field>
      <g-field-collapse
        label="边框样式"
      >
        <g-field
          :level="2"
          label="类型"
        >
          <g-select
            v-model="config.progress.border.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="宽度"
        >
          <g-input-number
            v-model="config.progress.border.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.progress.border.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.title.show"
      :toggle="true"
      label="标题"
    >
      <g-field
        :level="2"
        label="水平偏移量"
      >
        <g-input-number
          v-model="config.title.horizontal"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="垂直偏移量"
      >
        <g-input-number
          v-model="config.title.vertical"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="文本内容"
      >
        <g-input
          v-model="config.title.text"
        />
      </g-field>
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.title.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-select
            v-model="config.title.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
        <g-field
          :level="2"
          label="大小"
        >
          <g-input-number
            v-model="config.title.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.title.textStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.content.show"
      :toggle="true"
      label="内容"
    >
      <g-field
        :level="2"
        label="水平偏移量"
      >
        <g-input-number
          v-model="config.content.horizontal"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="垂直偏移量"
      >
        <g-input-number
          v-model="config.content.vertical"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.content.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-select
            v-model="config.content.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
        <g-field
          :level="2"
          label="大小"
        >
          <g-input-number
            v-model="config.content.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.content.textStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
  lineStyles,
  fontFamilys,
  fontWeights,
} from '@/data/select-options'
import { ProportionRing } from './proportion-ring'

export default defineComponent({
  name: 'VProportionRingProp',
  props: {
    com: {
      type: Object as PropType<ProportionRing>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    return {
      config,

      lineStyles,
      fontFamilys,
      fontWeights,
    }
  },
})
</script>
