<template>
  <div class="setting-panel-gui">
    <g-field-collapse
      label="背景"
    >
      <g-field
        :level="2"
        label="颜色"
      >
        <g-color-picker
          v-model="config.backgroundStyle.color"
        />
      </g-field>
      <g-field
        :level="2"
        label="透明度"
      >
        <g-input-number
          v-model="config.backgroundStyle.opacity"
          :min="0"
          :max="1"
          :step="0.1"
        />
      </g-field>
      <g-field-collapse
        label="边框"
      >
        <g-field
          :level="2"
          label="圆角"
        >
          <g-input-number
            v-model="config.backgroundStyle.border.radius"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.backgroundStyle.border.color"
          />
        </g-field>
        <g-field
          :level="2"
          label="样式"
        >
          <g-select
            v-model="config.backgroundStyle.border.style"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="宽度"
        >
          <g-input-number
            v-model="config.backgroundStyle.border.width"
            :min="0"
            :max="100"
            :step="1"
            suffix="px"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      label="输入框"
    >
      <g-field
        :level="2"
        label="字体"
      >
        <g-select
          v-model="config.input.fontFamily"
          :data="fontFamilys"
        />
      </g-field>
      <g-field
        :level="2"
        label="大小"
      >
        <g-input-number
          v-model="config.input.fontSize"
          :min="0"
          :max="100"
          :step="1"
          suffix="pt"
        />
      </g-field>
      <g-field
        :level="2"
        label="颜色"
      >
        <g-color-picker
          v-model="config.input.color"
        />
      </g-field>
      <g-field
        :level="2"
        label="粗细"
      >
        <g-select
          v-model="config.input.fontWeight"
          :data="fontWeights"
        />
      </g-field>
      <g-field
        :level="2"
        label="提示文本内容"
      >
        <g-input
          v-model="config.input.placeholder"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      label="下拉框"
    >
      <g-field-collapse
        label="面板背景"
      >
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.option.background.color"
          />
        </g-field>
        <g-field
          :level="2"
          label="透明度"
        >
          <g-input-number
            v-model="config.option.background.opacity"
            :min="0"
            :max="1"
            :step="0.1"
          />
        </g-field>
        <g-field-collapse
          label="边框"
        >
          <g-field
            :level="2"
            label="圆角"
          >
            <g-input-number
              v-model="config.option.background.border.radius"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
            />
          </g-field>
          <g-field
            :level="2"
            label="颜色"
          >
            <g-color-picker
              v-model="config.option.background.border.color"
            />
          </g-field>
          <g-field
            :level="2"
            label="样式"
          >
            <g-select
              v-model="config.option.background.border.style"
              :data="lineStyles"
            />
          </g-field>
          <g-field
            :level="2"
            label="宽度"
          >
            <g-input-number
              v-model="config.option.background.border.width"
              :min="0"
              :max="100"
              :step="1"
              suffix="px"
            />
          </g-field>
        </g-field-collapse>
      </g-field-collapse>
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.option.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="大小"
        >
          <g-input-number
            v-model="config.option.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.option.textStyle.color"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-select
            v-model="config.option.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
      </g-field-collapse>
      <g-field-collapse
        label="鼠标停留时"
      >
        <g-field
          :level="2"
          label="背景颜色"
        >
          <g-color-picker
            v-model="config.option.hovered.backgroundColor"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体颜色"
        >
          <g-color-picker
            v-model="config.option.hovered.fontColor"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
  lineStyles,
  fontFamilys,
  fontWeights,
} from '@/data/select-options'
import { dropDownList } from './drop-down-list'

export default defineComponent({
  name: 'VDropDownListProp',
  props: {
    com: {
      type: Object as PropType<dropDownList>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    return {
      config,

      lineStyles,
      fontFamilys,
      fontWeights,
    }
  },
})
</script>
