<template>
  <div class="setting-panel-gui">
    <g-field-collapse
      label="图形"
    >
      <g-field-collapse
        label="图表边距"
      >
        <g-field
          :level="2"
          label="上"
        >
          <g-input-number
            v-model="config.graphical.margin.top"
            :min="-9999"
            :max="9999"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="下"
        >
          <g-input-number
            v-model="config.graphical.margin.bottom"
            :min="-9999"
            :max="9999"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="左"
        >
          <g-input-number
            v-model="config.graphical.margin.left"
            :min="-9999"
            :max="9999"
            :step="1"
            suffix="px"
          />
        </g-field>
        <g-field
          :level="2"
          label="右"
        >
          <g-input-number
            v-model="config.graphical.margin.right"
            :min="-9999"
            :max="9999"
            :step="1"
            suffix="px"
          />
        </g-field>
      </g-field-collapse>
      <g-field
        :level="2"
        label="饼图半径"
      >
        <g-input-number
          v-model="config.graphical.pieRadius"
          :min="0"
          :max="100"
          :step="1"
          suffix="%"
        />
      </g-field>
      <g-field
        :level="2"
        label="饼图颜色"
      >
        <g-color-picker
          v-model="config.graphical.pieColor"
        />
      </g-field>
      <g-field-collapse
        label="饼图描边"
      >
        <g-field
          :level="2"
          label="线型"
        >
          <g-select
            v-model="config.graphical.pieLine.type"
            :data="lineStyles"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-input-number
            v-model="config.graphical.pieLine.width"
            :min="0"
            :max="100"
            :step="1"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.graphical.pieLine.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field
        :level="2"
        label="南丁格尔图"
      >
        <n-switch
          v-model:value="config.graphical.Nightingale"
        />
      </g-field>
      <!-- <g-field
        :level="2"
        label="彩色饼图"
      >
        <n-switch
          v-model:value="config.graphical.colour"
        />
      </g-field> -->
      <g-field-collapse
        v-model="config.graphical.colour"
        label="彩色饼图"
        mode="layout"
        default-layout="horizontal"
        :features="['vertical','horizontal','copy','add','remove']"
        :list="config.graphical.colorList"
        :min="1"
        :max="8"
        tab="颜色"
        :add-item="handleAddColor"
        :toggle="true"
      >
        <template #default="slotProps">
          <g-field
            :level="2"
            label="颜色"
          >
            <!-- {{ slotProps.item }} -->
            <g-color-picker
              v-model="slotProps.item.value"
            />
          </g-field>
        </template>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.legend.show"
      :toggle="true"
      label="图例"
    >
      <g-field
        :level="2"
        label="垂直"
      >
        <g-select
          v-model="config.legend.top"
          :data="vAligns"
        />
      </g-field>
      <g-field
        :level="2"
        label="水平"
      >
        <g-select
          v-model="config.legend.left"
          :data="hAligns"
        />
      </g-field>
      <g-field
        :level="2"
        label="布局方式"
      >
        <n-radio-group
          v-model:value="config.legend.orient"
          size="small"
        >
          <n-radio-button
            v-for="em in orients"
            :key="em.id"
            :value="em.id"
          >
            {{ em.value }}
          </n-radio-button>
        </n-radio-group>
      </g-field>
      <g-field
        :level="2"
        label="图文对齐"
      >
        <n-radio-group
          v-model:value="config.legend.align"
          size="small"
        >
          <n-radio-button
            value="left"
          >
            左对齐
          </n-radio-button>
          <n-radio-button
            value="right"
          >
            右对齐
          </n-radio-button>
        </n-radio-group>
      </g-field>
      <g-field
        :level="2"
        label="显示值"
      >
        <n-switch
          v-model:value="config.legend.showValue"
        />
      </g-field>
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.legend.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体粗细"
        >
          <g-select
            v-model="config.legend.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体大小"
        >
          <g-input-number
            v-model="config.legend.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.legend.textStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      label="提示框"
    >
      <g-field
        :level="2"
        label="触发方式"
      >
        <g-select
          v-model="config.tooltip.triggerOn"
          :data="[{ id:'mousemove',value:'鼠标悬停'},{ id:'click',value:'点击'}]"
        />
      </g-field>
      <g-field-collapse
        label="文本样式"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.tooltip.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体粗细"
        >
          <g-select
            v-model="config.tooltip.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体大小"
        >
          <g-input-number
            v-model="config.tooltip.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="字体颜色"
        >
          <g-color-picker
            v-model="config.tooltip.textStyle.color"
          />
        </g-field>
      </g-field-collapse>
      <g-field
        :level="2"
        label="标题间隔"
      >
        <g-input-number
          v-model="config.tooltip.padding"
          :min="-1000"
          :max="100"
          :step="1"
          suffix="px"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.content.enabled"
      label="内容"
      :toggle="true"
    >
      <g-field
        :level="2"
        label="内容间隔"
      >
        <g-input-number
          v-model="config.content.padding"
          :min="-1000"
          :max="100"
          :step="1"
          suffix="px"
        />
      </g-field>
      <g-field-collapse
        label="内容文本"
      >
        <g-field
          :level="2"
          label="字体"
        >
          <g-select
            v-model="config.content.textStyle.fontFamily"
            :data="fontFamilys"
          />
        </g-field>
        <g-field
          :level="2"
          label="粗细"
        >
          <g-select
            v-model="config.content.textStyle.fontWeight"
            :data="fontWeights"
          />
        </g-field>
        <g-field
          :level="2"
          label="大小"
        >
          <g-input-number
            v-model="config.content.textStyle.fontSize"
            :min="0"
            :max="100"
            :step="1"
            suffix="pt"
          />
        </g-field>
        <g-field
          :level="2"
          label="颜色"
        >
          <g-color-picker
            v-model="config.content.textStyle.color"
          />
        </g-field>
      </g-field-collapse>
    </g-field-collapse>
    <g-field-collapse
      v-model="config.animation.enabled"
      :toggle="true"
      label="动画"
    >
      <g-field
        :level="2"
        label="动画效果"
      >
        <g-select
          v-model="config.animation.easing"
          :data="animationEasings"
        />
      </g-field>
      <g-field
        :level="2"
        label="动画时长"
      >
        <g-input-number
          v-model="config.animation.duration"
          :min="0"
          :max="10000"
          :step="1"
          suffix="ms"
        />
      </g-field>
    </g-field-collapse>
    <g-field-collapse
      label="系列"
    >
      <g-field
        :level="2"
        label="系列名称"
      >
        <g-input
          v-model="config.series[0].name"
        />
      </g-field>
    </g-field-collapse>
  </div>
</template>

<script lang='ts'>
import { defineComponent, PropType, toRef } from 'vue'
import {
  lineStyles,
  vAligns,
  hAligns,
  fontFamilys,
  fontWeights,
  animationEasings,
  orients,
} from '@/data/select-options'
import { BasicPie,BasicPieSeries,colorItem } from './basic-pie'

export default defineComponent({
  name: 'VBasicPieProp',
  props: {
    com: {
      type: Object as PropType<BasicPie>,
      required: true,
    },
  },
  setup(props) {
    const config = toRef(props.com, 'config')

    const handleAddSeriesItem = () => {
      return new BasicPieSeries(`系列${config.value.series.length + 1}`)
    }

    const handleAddColor = () => {
      return new colorItem('#fff')
    }

    return {
      config,
      orients,

      lineStyles,
      vAligns,
      hAligns,
      fontFamilys,
      fontWeights,
      animationEasings,
      handleAddSeriesItem,
      handleAddColor,
    }
  },
})
</script>
